version: '2'
services:
    samplecodegen-app:
        image: samplecodegen
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samplecodegen-mysql:3306/samplecodegen?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    samplecodegen-mysql:
        extends:
            file: mysql.yml
            service: samplecodegen-mysql
